### ISSUE TITLE
Add support for adding wires devices

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/grafana-mqtt-data-source-build#1]
### Setup devices in MQTT connector 
User could add wires device id (MQTT topic)

![image](https://user-images.githubusercontent.com/18637436/92688264-6ab79100-f380-11ea-81ec-61cda61d7796.png)

### Setup devices in MQTT points from device point lists topic
It would be somthing like `deviceUUID/points`

![image](https://user-images.githubusercontent.com/18637436/92688472-bb2eee80-f380-11ea-8abb-e4c66338599f.png)

**Comment by RaiBnod** [comment]
**Implementation is done like this (once new release it made it will sync files on here):**

- Multiple Data Sources (one datasource for each devices and one of manual)

  ![image](https://user-images.githubusercontent.com/6800775/93119343-5e656800-f6e1-11ea-9dc5-5060efb73d1c.png)

- Configuration with Device ID

  ![image](https://user-images.githubusercontent.com/6800775/93118678-5bb64300-f6e0-11ea-9418-c757568dfc66.png)

- Configuration without Device ID

  ![image](https://user-images.githubusercontent.com/6800775/93118703-65d84180-f6e0-11ea-963b-d44efd5b001a.png)

- Selection with Device ID (currently that `Device ID = test/topics` topics has array as `["schedule","switch","multi-switch","slider"]`)

  ![image](https://user-images.githubusercontent.com/6800775/93118755-78eb1180-f6e0-11ea-9b17-7c422614d894.png)

- Manual topic Selection

  ![image](https://user-images.githubusercontent.com/6800775/93118782-83a5a680-f6e0-11ea-8cee-1c34ffc9e8d0.png)

**Comment by RaiBnod** [comment]
This one is fixed and hence closing down the ticket.
